services:
  # Application Service
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   environment:
  #     NODE_ENV: development
  #   command: npm run start:debug
  #   # Add restart policy to handle crashes/exits
  #   restart: unless-stopped
  #   # Enable watching file changes
  #   tty: true
  #   networks:
  #     app_net:
  #       ipv4_address: 172.20.0.4

  # Database Services
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - '5432:5432'
    networks:
      app_net:
        ipv4_address: 172.20.0.2

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      app_net:
        ipv4_address: 172.20.0.3

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
